[toolchain]
# Synchronize with https://github.com/nwtnni/cxlalloc
# Day before https://github.com/rust-lang/rust/commit/fe89962237e425f661ca36dd36113340188ac057
channel = "nightly-2024-07-17"
components = [
    "cargo",
    "clippy",
    "rustfmt",
    "rust-analyzer",
    "rust-docs",
    "rust-std",
    "rust-src",
]
